name: deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Run Workflow
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@master
      - name: Generic Run Command
        run: date
    env: # Or as an environment variable
      super_secret: ${{ secrets.TESTSECRET }}